In [3]:
import pandas as pd

In [4]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml

In [6]:
data = fetch_openml(name="california_housing",as_frame=True)

/tmp/pycharm_project_515/ml-env/lib64/python3.12/site-packages/sklearn/datasets/_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name california_housing exist. Versions may be fundamentally different, returning version 1. Available versions:
- version 1, status: active
  url: https://www.openml.org/search?type=data&id=43939
- version 7, status: active
  url: https://www.openml.org/search?type=data&id=44977

  warn(warning_msg)

In [12]:
print(type(data))
data

<class 'sklearn.utils._bunch.Bunch'>

{'data':        longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
 0        -122.23     37.88                  41          880           129.0
 1        -122.22     37.86                  21         7099          1106.0
 2        -122.24     37.85                  52         1467           190.0
 3        -122.25     37.85                  52         1274           235.0
 4        -122.25     37.85                  52         1627           280.0
 ...          ...       ...                 ...          ...             ...
 20635    -121.09     39.48                  25         1665           374.0
 20636    -121.21     39.49                  18          697           150.0
 20637    -121.22     39.43                  17         2254           485.0
 20638    -121.32     39.43                  18         1860           409.0
 20639    -121.24     39.37                  16         2785           616.0

        population  households  median_income ocean_proximity
 0             322         126         8.3252        NEAR BAY
 1            2401        1138         8.3014        NEAR BAY
 2             496         177         7.2574        NEAR BAY
 3             558         219         5.6431        NEAR BAY
 4             565         259         3.8462        NEAR BAY
 ...           ...         ...            ...             ...
 20635         845         330         1.5603          INLAND
 20636         356         114         2.5568          INLAND
 20637        1007         433         1.7000          INLAND
 20638         741         349         1.8672          INLAND
 20639        1387         530         2.3886          INLAND

 [20640 rows x 9 columns],
 'target': 0        452600
 1        358500
 2        352100
 3        341300
 4        342200
           ...
 20635     78100
 20636     77100
 20637     92300
 20638     84700
 20639     89400
 Name: median_house_value, Length: 20640, dtype: int64,
 'frame':        longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
 0        -122.23     37.88                  41          880           129.0
 1        -122.22     37.86                  21         7099          1106.0
 2        -122.24     37.85                  52         1467           190.0
 3        -122.25     37.85                  52         1274           235.0
 4        -122.25     37.85                  52         1627           280.0
 ...          ...       ...                 ...          ...             ...
 20635    -121.09     39.48                  25         1665           374.0
 20636    -121.21     39.49                  18          697           150.0
 20637    -121.22     39.43                  17         2254           485.0
 20638    -121.32     39.43                  18         1860           409.0
 20639    -121.24     39.37                  16         2785           616.0

        population  households  median_income  median_house_value  \
 0             322         126         8.3252              452600
 1            2401        1138         8.3014              358500
 2             496         177         7.2574              352100
 3             558         219         5.6431              341300
 4             565         259         3.8462              342200
 ...           ...         ...            ...                 ...
 20635         845         330         1.5603               78100
 20636         356         114         2.5568               77100
 20637        1007         433         1.7000               92300
 20638         741         349         1.8672               84700
 20639        1387         530         2.3886               89400

       ocean_proximity
 0            NEAR BAY
 1            NEAR BAY
 2            NEAR BAY
 3            NEAR BAY
 4            NEAR BAY
 ...               ...
 20635          INLAND
 20636          INLAND
 20637          INLAND
 20638          INLAND
 20639          INLAND

 [20640 rows x 10 columns],
 'categories': None,
 'feature_names': ['longitude',
  'latitude',
  'housing_median_age',
  'total_rooms',
  'total_bedrooms',
  'population',
  'households',
  'median_income',
  'ocean_proximity'],
 'target_names': ['median_house_value'],
 'DESCR': 'Median house prices for California districts derived from the 1990 census.\n\nDownloaded from openml.org.',
 'details': {'id': '43939',
  'name': 'california_housing',
  'version': '1',
  'description_version': '1',
  'format': 'ARFF',
  'upload_date': '2022-06-06T11:27:34',
  'licence': 'public',
  'url': 'https://openml.org/data/v1/download/22102987/california_housing.arff',
  'parquet_url': 'https://data.openml.org/datasets/0004/43939/dataset_43939.pq',
  'file_id': '22102987',
  'default_target_attribute': 'median_house_value',
  'visibility': 'public',
  'original_data_url': 'https://www.kaggle.com/datasets/camnugent/california-housing-prices',
  'status': 'active',
  'processing_date': '2022-06-06 11:28:03',
  'md5_checksum': '38cc9f7060e510f2f9f8072e250c5c35'},
 'url': 'https://www.openml.org/d/43939'}

In [14]:
housing_org = pd.DataFrame(data.data, columns=data.feature_names)

In [15]:
housing_org.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41,880,129.0,322,126,8.3252,NEAR BAY
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,NEAR BAY
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,NEAR BAY
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,NEAR BAY
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,NEAR BAY

In [16]:
housing = housing_org.copy()

In [18]:
housing.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  int64
 3   total_rooms         20640 non-null  int64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  int64
 6   households          20640 non-null  int64
 7   median_income       20640 non-null  float64
 8   ocean_proximity     20640 non-null  category
dtypes: category(1), float64(4), int64(4)
memory usage: 1.3 MB

In [19]:
housing.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100